version: '2.1'

services:
  #web:
  #  build:
  #    context: .
  #    dockerfile: 'Dockerfile'
  #  env_file:
  #    - '.env.dev'
  #  command: ['bin/rails', 's', '-b', '0.0.0.0']
  #  ports:
  #    - 3000:3000
  #  volumes:
  #    - .:/usr/src/app
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
  redis:
    image: redis:3.2.11
    ports:
      - 6379:6379
  neo4j:
    image: neo4j:3.3.5
    ports:
      - 7474:7474
      - 7687:7687

